server:
  port: 8091
  


spring:
  application:
    name: config-server-II
  cloud:
    config:
      server:
        git:
          uri: https://github.com/meavi05/config-repo.git
          clone-on-start: true
