#Start with a base image containing Java runtime
FROM openjdk:11-slim as build
WORKDIR application

ARG JAR_FILE=target/*.jar

COPY $JAR_FILE application.jar

RUN java -Djarmode=layertools -jar application.jar extract

FROM openjdk:11-slim
WORKDIR application
COPY --from=build application/dependencies/ ./
COPY --from=build application/spring-boot-loader/ ./
COPY --from=build application/snapshot-dependencies/ ./
COPY --from=build application/application/ ./

ENTRYPOINT ["java", "org.springframework.boot.loader.JarLauncher"]
# Add Maintainer Info
LABEL maintainer="Avinash Singh <meavinash05@gmail.com>"
